### PR TITLE
Fix source / destination bug

### PR DESCRIPTION
**Pull request by igitur**
Refer to https://github.com/OpenDBDiff/OpenDBDiff/pull/39#issuecomment-357237691

### CODE REVIEW

**Comment by igitur** [comment]
@ironicnet Would you please check whether this breaks OCDB or not?

**Comment by igitur** [comment]
The OCDB console app was also broken (I broke it). Now fixed. But I also renamed the command line parameters to `before` and `after` to make it clear what the generated script will do. Well, hopefully it's clear now. Waiting for feedback before merging this. cc @ironicnet

**Comment by igitur** [comment]
@ironicnet Have you had a chance to look at this PR?

**Comment by ironicnet** [comment]
Sorry @igitur  i've been hit by lot of work and ended up a little burned out. I wan't able to check github nor the issue. 
I'm just catching up with the github issues. Sorry for all the mess

**Pull request merged**
