### PR TITLE
Features/split frontend generates

### PR DESCRIPTION
**Pull request by ironicnet**
This maybe it's a big refactor, but i was in the middle while writing #21 

Decoupled the DBDiff project from the DBDiff.Schema.SQLServer / DBDiff.Schema.SQLServer.Generates.

Basically, if you want to Add a new DatabaseEngine type (like MySQL or SyBase). You should implement the IProjectHandler interfaces in DBDiff.Front.

That way each "Database Engine" would have a "Plugin" associated.

Let me see what you guys think.

### CODE REVIEW

**Comment by jspraul** [comment]
Thanks for doing all of this. I am not super-qualified on any of this, so please do not consider any of these preliminary comments to be requests to make any changes. The separation is necessary, and can be tweaked/improved as needed.

My initial gut reaction is that magic strings and reflection might be pushing what would have been compile errors into runtime errors. The strings part is always a balance between speed of development vs. things like constants and/or enums. Reflection may indicate that it would be best to find a popular, lightweight dependency injection framework that is production-server-friendly (supporting "old .NET versions" rather than requiring cutting-edge).

Don't be afraid to drop SQLite as a dependency for the configuration storage as well, though that should probably be a separate pull request. I think people who've changed this used XML back in the day; JSON is more popular now but I'm don't know enough about the open source C# world to know if there is some de-facto "standard" or fully-managed dependency that makes this easy.

I didn't dig in too much but how does this change affect the command line project? Can these improvements help make it possible to use the GUI to setup a comparison, then use the command line tool to repeat it?

My primary response is that I appreciate the effort you are putting into this. It would be nice to get a bit more feedback, but this tool is so neglected that even I don't really feel like I have the authority to stop anyone who isn't breaking existing functionality.

**Comment by ironicnet** [comment]
> I didn't dig in too much but how does this change affect the command line project?

It shouldn't affect the command line project that much. I really didn't test the command line project. I'll address that.

> Can these improvements help make it possible to use the GUI to setup a comparison, then use the command line tool to repeat it?

I think so, the only problem that i see. Is that we are not persisting the "Options" associated with the project. There is an issue referencing this:  #1 . Once those options are persisted, it should be almost identical.

> My primary response is that I appreciate the effort you are putting into this. It would be nice to get a bit more feedback, but this tool is so neglected that even I don't really feel like I have the authority to stop anyone who isn't breaking existing functionality.

I totally understand this, that's why I requested your review. I don't want to break existing functionality or any use case.

**Comment by ironicnet** [comment]
@jspraul I removed the reflection part. So instead of loading the assemblies via name. I'm just instancing them.

Just checked the console project. I didn't decouple it as I did with the DBDiff main app. So it's working as it was already.

**Comment by jspraul** [comment]
I think there has been plent of time for anyone interested to comment.

If for some reason you want to push to a new 'unstable' branch, I will setup a CI build for that and link it on the main page. I haven't sorted out why it's not picking up check-ins on master automatically, so no guarantees.

Thanks again for taking the time to contribute.

**Comment by igitur** [comment]
@ironicnet Were all the changes to `PrincipalForm.Designer.cs` deliberate? I suspect many of them were changes generated by the Visual Studio designer. I'm struggling to figure out which were intended changes.

**Comment by ironicnet** [comment]
I think that change comes from #25 (https://github.com/OpenDBDiff/OpenDBDiff/pull/25) 
Didn't realize it looked like that...

**Comment by igitur** [comment]
Can you try revert all the unintended changes?

**Comment by ironicnet** [comment]
I can fix the gap, and anchor it correctly. Or which unintended changes do you refer to?.
I modified the Principal Form and modified controls on it, which always triggers the designer changes.

**Comment by ironicnet** [comment]
I created the PR #52 . I don't know if those are all the changes that you need.

**Pull request merged**
