### PR TITLE
Fix speed problem to find item. Now there is a check if exists an obj…

### PR DESCRIPTION
**Pull request by evangelalessandro**
Every time find an item in a collation and there is nt, every time spend 10 ms to create an exception.

### CODE REVIEW

**Comment by igitur** [comment]
Thanks for your contributions. Please adjust to use the same whitespace settings as the original file. Your changes mess up the indentation.

**Comment by evangelalessandro** [comment]
I know but my company use this one, next time I will use a vm... Thank you!

Il 01/giu/2017 16:29, "Francois Botha" <notifications@github.com> ha
scritto:

Thanks for your contributions. Please adjust to use the same whitespace
settings as the original file. Your changes mess up the indentation.

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub
<https://github.com/OpenDBDiff/OpenDBDiff/pull/5#issuecomment-305510723>,
or mute the thread

**Comment by igitur** [comment]
You can't change your whitespace settings?!

**Comment by evangelalessandro** [comment]
Sure I will try

Il 02/giu/2017 04:37 PM, "Francois Botha" <notifications@github.com> ha
scritto:

You can't change your whitespace settings?!

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub
<https://github.com/OpenDBDiff/OpenDBDiff/pull/5#issuecomment-305807047>,
or mute the thread

**Comment by evangelalessandro** [comment]
i reformat document!

**Comment by igitur** [comment]
Now you changed the format of the entire file, which makes it very difficult to identify what you actually changed. Please revert your changes, and add your own changes with the correct whitespace/indentation settings, but leave the rest of the files unchanged. This is standard practice for submitting pull requests.

**Comment by evangelalessandro** [comment]
Please check if it's ok now!
thk, it's my first contribution and i don't know what i must to do and how!

**Comment by jspraul** [comment]
First, thanks for your work on this. I really appreciate how you've incorporated the feedback already given. I apologize for the delay but I usually wait for a batch of stuff to add at once.

Second, I am trying to understand when this becomes a problem. My gut feeling is that the items not being found is only an issue when some dependency is not found/inaccessible (due to permissions). This is a recurring problem reported on the [CodePlex issues](http://opendbdiff.codeplex.com/workitem/list/basic?keywords=NullReferenceException), and seems to most often happen for indexes. Perhaps it could also happen when certain types of objects are not being processed per the settings?

Third, when submitting performance optimizations, it would be helpful to include a before/after comparison of the performance. I am not asking you to do this in this case, it is more something to keep in mind in the future.

Thanks for taking the time to work through getting this fix into the project!

PS. For my own future reference since I went looking today, there is a fix re:index errors "[Fix ordering of constraint columns. Use referenceID instead of KeyOrder](https://github.com/facingup/opendbdiff-old/commits/)".

**Comment by evangelalessandro** [comment]
I check in my medium db and for each time that create an exception spend 15
ms, 15 ms x 10000 time , there's a lot of waste time!!!

Thank you!!

Il 11/ago/2017 17:05, "jspraul" <notifications@github.com> ha scritto:

**Pull request merged**
