### PR TITLE
Upgrade ScintillaNet to v3.6.3

### PR DESCRIPTION
**Pull request by igitur**
Upgrade ScintillaNet to a .NET 3.5 build of https://github.com/jacobslusser/ScintillaNET

Had to do manual build because the NuGet package doesn't contain the net35 build yet. Refer https://github.com/jacobslusser/ScintillaNET/issues/370

This PR needs thorough testing before merging.

It also paves the way for possible future upgrade to net45+.

### CODE REVIEW

**Comment by ironicnet** [comment]
It would be great to be able to switch to WPF in the future

**Comment by ironicnet** [comment]
Maybe this PR can go to the beta version?

**Comment by igitur** [comment]
I've been testing this for the past week and I don't notice any issues. Will squash and merge.

**Comment by igitur** [comment]
Shit. I merged into master instead of develop. Will fix.

**Pull request merged**
