### PR TITLE
Rename all DBDiff references to OpenDBDiff

### PR DESCRIPTION
**Pull request by igitur**
This will break a lot of people's branches. But I got tired of seeing discrepancies between DBDiff and OpenDBDiff. This PR fixes it. It renames all files and code references to use only OpenDBDiff.

Comments welcome.

### CODE REVIEW

**Comment by ironicnet** [comment]
I would say, Merge it!... if it's breaking someone's build, it should be easily fixed as it only involves a Search and Replace

**Comment by igitur** [comment]
I'm also using this PR to test the CI integration, which I see isn't working yet.

**Comment by igitur** [comment]
Ok, merged. My apologies if I cause havoc with this one.

**Comment by igitur** [comment]
CI also working now.

**Pull request merged**
